export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


export const ADD_STUDENT_INFO = "ADD_STUDENT_INFO";
export const DELETE_STUDENT_INFO = " DELETE_STUDENT_INFO";
export const EDIT_STUDENT_INFO = " EDIT_STUDENT_INFO";


export const ADD_EMPLOYEE_INFO = "ADD_EMPLOYEE_INFO";
export const DELETE_EMPLOYEE_INFO = "DELETE_EMPLOYEE_INFO";
export const EDIT_EMPLOYEE_INFO = "EDIT_EMPLOYEE_INFO";

